### PR TITLE
Node0.10.x

### PR DESCRIPTION
**Pull request by akkumar**
Using node-gyp build system as opposed to node-waf.

### CODE REVIEW

**Comment by arboleya** [comment]
+1

Waiting for it!

**Comment by arboleya** [comment]
@akkumar Nice PR btw.

**Comment by taxilian** [comment]
+1 please get this in... it's messing up my build scripts :-(

**Comment by akkumar** [comment]
This seems the project is inactive for a good 3 years. Is there any supported fork ?

**Pull request closed without merging**
