### PR TITLE
Use node-gyp instead of node-waf

### PR DESCRIPTION
**Pull request by soarez**
node-waf was deprecated with Node 0.8; its replacement, node-gyp, cannot build rbytes either .

http://stackoverflow.com/questions/16317976/node-waf-not-found

This patch makes rbytes work with node-gyp.

### CODE REVIEW

**Comment by kmlx** [comment]
I've applied your patch, but binding.gyp is missing, so the build fails.

**Comment by soarez** [comment]
Sorry, forgot to check it in.

**Comment by soarez** [comment]
Meanwhile, I solved the problem by uninstalling node, installing the latest v0.8 and then installing the latest v0.10 on top. Then you get node v0.10 and still keep node-waf.

**Comment by soarez** [comment]
v1.0.0 uploaded to npm. Update to fix.

**Pull request closed without merging**
